# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'todo_task' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for todo_task
  pod 'IQKeyboardManagerSwift'

  target 'todo_taskTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'todo_taskUITests' do
    # Pods for testing
  end

end
